### ISSUE TITLE
Checkout discount code input styling on mobile

### ISSUE THREAD

**Issue by davidsherlock** [bigboxwc/bigbox#128]
### Expected Behavior

It looks like the checkout discount code is not properly styled on the demo site/theme. I would expect this to look the same (with the border) as the totals below to keep it cohesive design wise.

### Actual Behavior

See screenshot for reference:

<img width="396" alt="screenshot 2019-02-16 22 21 18" src="https://user-images.githubusercontent.com/22668877/52911744-7e843980-32a8-11e9-84b9-ac0501188284.png">

**Comment by spencerfinnell** [comment]
The original intended design is correct on the desktop: https://cloudup.com/crGCjKSycNb -- mobile just needs some spacing updates.

To match the "Totals" box you can add the `.card` class to the coupon `form` wrapper. 

https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/form-coupon.php#L29
